name: Lint HTML Files on PR

on:
  pull_request:
    branches:
      - gh-pages  # Trigger on pull requests targeting the gh-pages branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install linthtml
        run: npm install htmlhint -g

      - name: Linthtml
        run: | 
               htmlhint '*.html'
               htmlhint 'Archie/*.html'
               htmlhint 'Max/*html'
